### ISSUE TITLE
Create a Bandit class

### ISSUE THREAD

**Issue by Aniq55** [Aniq55/pyMAB#2]
Create a class named `Bandit` with the following properties:
* id [for identification]
* p_reward [probability that the reward = 1]
Define functions for the class:
* get_reward() - returns the reward by feeding p_reward in a bernoulli distribution

**Comment by iTanuj** [comment]
size of distribution? and the reward value is sum of 1's in that?

**Comment by Aniq55** [comment]
just return one value.

It's a random function. So it will return a random value either one or zero, where the probability of getting a one is equal to `p_reward`.

Is it clear now?

**Comment by iTanuj** [comment]
yes, thanks
