### ISSUE TITLE
Create the Agent Class

### ISSUE THREAD

**Issue by Aniq55** [Aniq55/pyMAB#3]
create class for an agent with the following properties
* `id` for identification
* `bandits` contains the list of Bandit objects
* `strategy_name` initialize to None for now

Functions:
```
def strategy(self):
    pass
```
The idea is to create a library of all strategies and choosing the function accordingly

**Comment by Visual-mov** [comment]
Can you elaborate on what you'd like to be done?

**Comment by Aniq55** [comment]
> Can you elaborate on what you'd like to be done?

Its for Multi-armed bandits.
I want a framework to enable the calculations of MAB.
In MAB, there are multiple bandits and one agent, which chooses from among those bandits.

For now, the strategy function can be left empty.

This issue is only for the skeleton. Also have a look at #2 

Once these are done, I'll create an issue linking to various algos one can implement in the library, like:
* Thompson Sampling (TS)
* UCB
* Discounted TS
and many more
